//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("requerimientosModel", "FK_usuario_perfil1", "perfil", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SisReq.Models.perfil), "usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SisReq.Models.usuario), true)]
[assembly: EdmRelationshipAttribute("requerimientosModel", "FK_proyectoxusuario_perfilproyecto", "perfilproyecto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SisReq.Models.perfilproyecto), "proyectoxusuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SisReq.Models.proyectoxusuario), true)]
[assembly: EdmRelationshipAttribute("requerimientosModel", "FK_proyectoxusuario_proyecto", "proyecto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SisReq.Models.proyecto), "proyectoxusuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SisReq.Models.proyectoxusuario), true)]
[assembly: EdmRelationshipAttribute("requerimientosModel", "FK_Requerimiento_proyecto", "proyecto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SisReq.Models.proyecto), "Requerimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SisReq.Models.Requerimiento), true)]
[assembly: EdmRelationshipAttribute("requerimientosModel", "FK_proyectoxusuario_usuario", "usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SisReq.Models.usuario), "proyectoxusuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SisReq.Models.proyectoxusuario), true)]
[assembly: EdmRelationshipAttribute("requerimientosModel", "FK_Requerimiento_subtiporequerimiento", "subtiporequerimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SisReq.Models.subtiporequerimiento), "Requerimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SisReq.Models.Requerimiento), true)]
[assembly: EdmRelationshipAttribute("requerimientosModel", "FK_Requerimiento_usuario", "usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SisReq.Models.usuario), "Requerimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SisReq.Models.Requerimiento), true)]
[assembly: EdmRelationshipAttribute("requerimientosModel", "FK_Requerimiento_usuario1", "usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SisReq.Models.usuario), "Requerimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SisReq.Models.Requerimiento), true)]
[assembly: EdmRelationshipAttribute("requerimientosModel", "FK_suttiporequerimiento_tiporequerimiento", "tiporequerimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SisReq.Models.tiporequerimiento), "subtiporequerimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SisReq.Models.subtiporequerimiento), true)]

#endregion

namespace SisReq.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class requerimientosEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new requerimientosEntities object using the connection string found in the 'requerimientosEntities' section of the application configuration file.
        /// </summary>
        public requerimientosEntities() : base("name=requerimientosEntities", "requerimientosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new requerimientosEntities object.
        /// </summary>
        public requerimientosEntities(string connectionString) : base(connectionString, "requerimientosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new requerimientosEntities object.
        /// </summary>
        public requerimientosEntities(EntityConnection connection) : base(connection, "requerimientosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<perfil> perfil
        {
            get
            {
                if ((_perfil == null))
                {
                    _perfil = base.CreateObjectSet<perfil>("perfil");
                }
                return _perfil;
            }
        }
        private ObjectSet<perfil> _perfil;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<perfilproyecto> perfilproyecto
        {
            get
            {
                if ((_perfilproyecto == null))
                {
                    _perfilproyecto = base.CreateObjectSet<perfilproyecto>("perfilproyecto");
                }
                return _perfilproyecto;
            }
        }
        private ObjectSet<perfilproyecto> _perfilproyecto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<proyecto> proyecto
        {
            get
            {
                if ((_proyecto == null))
                {
                    _proyecto = base.CreateObjectSet<proyecto>("proyecto");
                }
                return _proyecto;
            }
        }
        private ObjectSet<proyecto> _proyecto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<proyectoxusuario> proyectoxusuario
        {
            get
            {
                if ((_proyectoxusuario == null))
                {
                    _proyectoxusuario = base.CreateObjectSet<proyectoxusuario>("proyectoxusuario");
                }
                return _proyectoxusuario;
            }
        }
        private ObjectSet<proyectoxusuario> _proyectoxusuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Requerimiento> Requerimiento
        {
            get
            {
                if ((_Requerimiento == null))
                {
                    _Requerimiento = base.CreateObjectSet<Requerimiento>("Requerimiento");
                }
                return _Requerimiento;
            }
        }
        private ObjectSet<Requerimiento> _Requerimiento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<subtiporequerimiento> subtiporequerimiento
        {
            get
            {
                if ((_subtiporequerimiento == null))
                {
                    _subtiporequerimiento = base.CreateObjectSet<subtiporequerimiento>("subtiporequerimiento");
                }
                return _subtiporequerimiento;
            }
        }
        private ObjectSet<subtiporequerimiento> _subtiporequerimiento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tiporequerimiento> tiporequerimiento
        {
            get
            {
                if ((_tiporequerimiento == null))
                {
                    _tiporequerimiento = base.CreateObjectSet<tiporequerimiento>("tiporequerimiento");
                }
                return _tiporequerimiento;
            }
        }
        private ObjectSet<tiporequerimiento> _tiporequerimiento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuario> usuario
        {
            get
            {
                if ((_usuario == null))
                {
                    _usuario = base.CreateObjectSet<usuario>("usuario");
                }
                return _usuario;
            }
        }
        private ObjectSet<usuario> _usuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<log_requerimientos> log_requerimientos
        {
            get
            {
                if ((_log_requerimientos == null))
                {
                    _log_requerimientos = base.CreateObjectSet<log_requerimientos>("log_requerimientos");
                }
                return _log_requerimientos;
            }
        }
        private ObjectSet<log_requerimientos> _log_requerimientos;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the perfil EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToperfil(perfil perfil)
        {
            base.AddObject("perfil", perfil);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the perfilproyecto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToperfilproyecto(perfilproyecto perfilproyecto)
        {
            base.AddObject("perfilproyecto", perfilproyecto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the proyecto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproyecto(proyecto proyecto)
        {
            base.AddObject("proyecto", proyecto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the proyectoxusuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproyectoxusuario(proyectoxusuario proyectoxusuario)
        {
            base.AddObject("proyectoxusuario", proyectoxusuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Requerimiento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRequerimiento(Requerimiento requerimiento)
        {
            base.AddObject("Requerimiento", requerimiento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the subtiporequerimiento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosubtiporequerimiento(subtiporequerimiento subtiporequerimiento)
        {
            base.AddObject("subtiporequerimiento", subtiporequerimiento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tiporequerimiento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotiporequerimiento(tiporequerimiento tiporequerimiento)
        {
            base.AddObject("tiporequerimiento", tiporequerimiento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuario(usuario usuario)
        {
            base.AddObject("usuario", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the log_requerimientos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolog_requerimientos(log_requerimientos log_requerimientos)
        {
            base.AddObject("log_requerimientos", log_requerimientos);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="requerimientosModel", Name="log_requerimientos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class log_requerimientos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new log_requerimientos object.
        /// </summary>
        /// <param name="idrequerimiento">Initial value of the idrequerimiento property.</param>
        public static log_requerimientos Createlog_requerimientos(global::System.Int32 idrequerimiento)
        {
            log_requerimientos log_requerimientos = new log_requerimientos();
            log_requerimientos.idrequerimiento = idrequerimiento;
            return log_requerimientos;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idrequerimiento
        {
            get
            {
                return _idrequerimiento;
            }
            set
            {
                if (_idrequerimiento != value)
                {
                    OnidrequerimientoChanging(value);
                    ReportPropertyChanging("idrequerimiento");
                    _idrequerimiento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idrequerimiento");
                    OnidrequerimientoChanged();
                }
            }
        }
        private global::System.Int32 _idrequerimiento;
        partial void OnidrequerimientoChanging(global::System.Int32 value);
        partial void OnidrequerimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                OncodigoChanging(value);
                ReportPropertyChanging("codigo");
                _codigo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("codigo");
                OncodigoChanged();
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idproyecto
        {
            get
            {
                return _idproyecto;
            }
            set
            {
                OnidproyectoChanging(value);
                ReportPropertyChanging("idproyecto");
                _idproyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idproyecto");
                OnidproyectoChanged();
            }
        }
        private Nullable<global::System.Int32> _idproyecto;
        partial void OnidproyectoChanging(Nullable<global::System.Int32> value);
        partial void OnidproyectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private Nullable<global::System.Byte> _status;
        partial void OnstatusChanging(Nullable<global::System.Byte> value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String prioridad
        {
            get
            {
                return _prioridad;
            }
            set
            {
                OnprioridadChanging(value);
                ReportPropertyChanging("prioridad");
                _prioridad = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("prioridad");
                OnprioridadChanged();
            }
        }
        private global::System.String _prioridad;
        partial void OnprioridadChanging(global::System.String value);
        partial void OnprioridadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idsubtiporequerimiento
        {
            get
            {
                return _idsubtiporequerimiento;
            }
            set
            {
                OnidsubtiporequerimientoChanging(value);
                ReportPropertyChanging("idsubtiporequerimiento");
                _idsubtiporequerimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idsubtiporequerimiento");
                OnidsubtiporequerimientoChanged();
            }
        }
        private Nullable<global::System.Int32> _idsubtiporequerimiento;
        partial void OnidsubtiporequerimientoChanging(Nullable<global::System.Int32> value);
        partial void OnidsubtiporequerimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> update_idusuario
        {
            get
            {
                return _update_idusuario;
            }
            set
            {
                Onupdate_idusuarioChanging(value);
                ReportPropertyChanging("update_idusuario");
                _update_idusuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("update_idusuario");
                Onupdate_idusuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _update_idusuario;
        partial void Onupdate_idusuarioChanging(Nullable<global::System.Int32> value);
        partial void Onupdate_idusuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> insert_idusuario
        {
            get
            {
                return _insert_idusuario;
            }
            set
            {
                Oninsert_idusuarioChanging(value);
                ReportPropertyChanging("insert_idusuario");
                _insert_idusuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("insert_idusuario");
                Oninsert_idusuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _insert_idusuario;
        partial void Oninsert_idusuarioChanging(Nullable<global::System.Int32> value);
        partial void Oninsert_idusuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> insert_date
        {
            get
            {
                return _insert_date;
            }
            set
            {
                Oninsert_dateChanging(value);
                ReportPropertyChanging("insert_date");
                _insert_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("insert_date");
                Oninsert_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _insert_date;
        partial void Oninsert_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oninsert_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> update_date
        {
            get
            {
                return _update_date;
            }
            set
            {
                Onupdate_dateChanging(value);
                ReportPropertyChanging("update_date");
                _update_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("update_date");
                Onupdate_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _update_date;
        partial void Onupdate_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onupdate_dateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="requerimientosModel", Name="perfil")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class perfil : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new perfil object.
        /// </summary>
        /// <param name="idperfil">Initial value of the idperfil property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        public static perfil Createperfil(global::System.Int32 idperfil, global::System.String nombre)
        {
            perfil perfil = new perfil();
            perfil.idperfil = idperfil;
            perfil.nombre = nombre;
            return perfil;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idperfil
        {
            get
            {
                return _idperfil;
            }
            set
            {
                if (_idperfil != value)
                {
                    OnidperfilChanging(value);
                    ReportPropertyChanging("idperfil");
                    _idperfil = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idperfil");
                    OnidperfilChanged();
                }
            }
        }
        private global::System.Int32 _idperfil;
        partial void OnidperfilChanging(global::System.Int32 value);
        partial void OnidperfilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_usuario_perfil1", "usuario")]
        public EntityCollection<usuario> usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<usuario>("requerimientosModel.FK_usuario_perfil1", "usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<usuario>("requerimientosModel.FK_usuario_perfil1", "usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="requerimientosModel", Name="perfilproyecto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class perfilproyecto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new perfilproyecto object.
        /// </summary>
        /// <param name="idperfilproyecto">Initial value of the idperfilproyecto property.</param>
        public static perfilproyecto Createperfilproyecto(global::System.Int32 idperfilproyecto)
        {
            perfilproyecto perfilproyecto = new perfilproyecto();
            perfilproyecto.idperfilproyecto = idperfilproyecto;
            return perfilproyecto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idperfilproyecto
        {
            get
            {
                return _idperfilproyecto;
            }
            set
            {
                if (_idperfilproyecto != value)
                {
                    OnidperfilproyectoChanging(value);
                    ReportPropertyChanging("idperfilproyecto");
                    _idperfilproyecto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idperfilproyecto");
                    OnidperfilproyectoChanged();
                }
            }
        }
        private global::System.Int32 _idperfilproyecto;
        partial void OnidperfilproyectoChanging(global::System.Int32 value);
        partial void OnidperfilproyectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_proyectoxusuario_perfilproyecto", "proyectoxusuario")]
        public EntityCollection<proyectoxusuario> proyectoxusuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<proyectoxusuario>("requerimientosModel.FK_proyectoxusuario_perfilproyecto", "proyectoxusuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<proyectoxusuario>("requerimientosModel.FK_proyectoxusuario_perfilproyecto", "proyectoxusuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="requerimientosModel", Name="proyecto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class proyecto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new proyecto object.
        /// </summary>
        /// <param name="idproyecto">Initial value of the idproyecto property.</param>
        public static proyecto Createproyecto(global::System.Int32 idproyecto)
        {
            proyecto proyecto = new proyecto();
            proyecto.idproyecto = idproyecto;
            return proyecto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idproyecto
        {
            get
            {
                return _idproyecto;
            }
            set
            {
                if (_idproyecto != value)
                {
                    OnidproyectoChanging(value);
                    ReportPropertyChanging("idproyecto");
                    _idproyecto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idproyecto");
                    OnidproyectoChanged();
                }
            }
        }
        private global::System.Int32 _idproyecto;
        partial void OnidproyectoChanging(global::System.Int32 value);
        partial void OnidproyectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechainicio
        {
            get
            {
                return _fechainicio;
            }
            set
            {
                OnfechainicioChanging(value);
                ReportPropertyChanging("fechainicio");
                _fechainicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechainicio");
                OnfechainicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechainicio;
        partial void OnfechainicioChanging(Nullable<global::System.DateTime> value);
        partial void OnfechainicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] descripcion
        {
            get
            {
                return StructuralObject.GetValidValue(_descripcion);
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.Byte[] _descripcion;
        partial void OndescripcionChanging(global::System.Byte[] value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_proyectoxusuario_proyecto", "proyectoxusuario")]
        public EntityCollection<proyectoxusuario> proyectoxusuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<proyectoxusuario>("requerimientosModel.FK_proyectoxusuario_proyecto", "proyectoxusuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<proyectoxusuario>("requerimientosModel.FK_proyectoxusuario_proyecto", "proyectoxusuario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_Requerimiento_proyecto", "Requerimiento")]
        public EntityCollection<Requerimiento> Requerimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Requerimiento>("requerimientosModel.FK_Requerimiento_proyecto", "Requerimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Requerimiento>("requerimientosModel.FK_Requerimiento_proyecto", "Requerimiento", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="requerimientosModel", Name="proyectoxusuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class proyectoxusuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new proyectoxusuario object.
        /// </summary>
        /// <param name="idusuario">Initial value of the idusuario property.</param>
        /// <param name="idperfilproyecto">Initial value of the idperfilproyecto property.</param>
        public static proyectoxusuario Createproyectoxusuario(global::System.Int32 idusuario, global::System.Int32 idperfilproyecto)
        {
            proyectoxusuario proyectoxusuario = new proyectoxusuario();
            proyectoxusuario.idusuario = idusuario;
            proyectoxusuario.idperfilproyecto = idperfilproyecto;
            return proyectoxusuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idproyecto
        {
            get
            {
                return _idproyecto;
            }
            set
            {
                OnidproyectoChanging(value);
                ReportPropertyChanging("idproyecto");
                _idproyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idproyecto");
                OnidproyectoChanged();
            }
        }
        private Nullable<global::System.Int32> _idproyecto;
        partial void OnidproyectoChanging(Nullable<global::System.Int32> value);
        partial void OnidproyectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idusuario
        {
            get
            {
                return _idusuario;
            }
            set
            {
                if (_idusuario != value)
                {
                    OnidusuarioChanging(value);
                    ReportPropertyChanging("idusuario");
                    _idusuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idusuario");
                    OnidusuarioChanged();
                }
            }
        }
        private global::System.Int32 _idusuario;
        partial void OnidusuarioChanging(global::System.Int32 value);
        partial void OnidusuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idperfilproyecto
        {
            get
            {
                return _idperfilproyecto;
            }
            set
            {
                if (_idperfilproyecto != value)
                {
                    OnidperfilproyectoChanging(value);
                    ReportPropertyChanging("idperfilproyecto");
                    _idperfilproyecto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idperfilproyecto");
                    OnidperfilproyectoChanged();
                }
            }
        }
        private global::System.Int32 _idperfilproyecto;
        partial void OnidperfilproyectoChanging(global::System.Int32 value);
        partial void OnidperfilproyectoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_proyectoxusuario_perfilproyecto", "perfilproyecto")]
        public perfilproyecto perfilproyecto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<perfilproyecto>("requerimientosModel.FK_proyectoxusuario_perfilproyecto", "perfilproyecto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<perfilproyecto>("requerimientosModel.FK_proyectoxusuario_perfilproyecto", "perfilproyecto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<perfilproyecto> perfilproyectoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<perfilproyecto>("requerimientosModel.FK_proyectoxusuario_perfilproyecto", "perfilproyecto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<perfilproyecto>("requerimientosModel.FK_proyectoxusuario_perfilproyecto", "perfilproyecto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_proyectoxusuario_proyecto", "proyecto")]
        public proyecto proyecto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<proyecto>("requerimientosModel.FK_proyectoxusuario_proyecto", "proyecto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<proyecto>("requerimientosModel.FK_proyectoxusuario_proyecto", "proyecto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<proyecto> proyectoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<proyecto>("requerimientosModel.FK_proyectoxusuario_proyecto", "proyecto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<proyecto>("requerimientosModel.FK_proyectoxusuario_proyecto", "proyecto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_proyectoxusuario_usuario", "usuario")]
        public usuario usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("requerimientosModel.FK_proyectoxusuario_usuario", "usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("requerimientosModel.FK_proyectoxusuario_usuario", "usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuario> usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("requerimientosModel.FK_proyectoxusuario_usuario", "usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuario>("requerimientosModel.FK_proyectoxusuario_usuario", "usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="requerimientosModel", Name="Requerimiento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Requerimiento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Requerimiento object.
        /// </summary>
        /// <param name="idrequerimiento">Initial value of the idrequerimiento property.</param>
        /// <param name="idproyecto">Initial value of the idproyecto property.</param>
        public static Requerimiento CreateRequerimiento(global::System.Int32 idrequerimiento, global::System.Int32 idproyecto)
        {
            Requerimiento requerimiento = new Requerimiento();
            requerimiento.idrequerimiento = idrequerimiento;
            requerimiento.idproyecto = idproyecto;
            return requerimiento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idrequerimiento
        {
            get
            {
                return _idrequerimiento;
            }
            set
            {
                if (_idrequerimiento != value)
                {
                    OnidrequerimientoChanging(value);
                    ReportPropertyChanging("idrequerimiento");
                    _idrequerimiento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idrequerimiento");
                    OnidrequerimientoChanged();
                }
            }
        }
        private global::System.Int32 _idrequerimiento;
        partial void OnidrequerimientoChanging(global::System.Int32 value);
        partial void OnidrequerimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                OncodigoChanging(value);
                ReportPropertyChanging("codigo");
                _codigo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("codigo");
                OncodigoChanged();
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idproyecto
        {
            get
            {
                return _idproyecto;
            }
            set
            {
                OnidproyectoChanging(value);
                ReportPropertyChanging("idproyecto");
                _idproyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idproyecto");
                OnidproyectoChanged();
            }
        }
        private global::System.Int32 _idproyecto;
        partial void OnidproyectoChanging(global::System.Int32 value);
        partial void OnidproyectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> insert_date
        {
            get
            {
                return _insert_date;
            }
            set
            {
                Oninsert_dateChanging(value);
                ReportPropertyChanging("insert_date");
                _insert_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("insert_date");
                Oninsert_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _insert_date;
        partial void Oninsert_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oninsert_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> update_date
        {
            get
            {
                return _update_date;
            }
            set
            {
                Onupdate_dateChanging(value);
                ReportPropertyChanging("update_date");
                _update_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("update_date");
                Onupdate_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _update_date;
        partial void Onupdate_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onupdate_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> insert_idusuario
        {
            get
            {
                return _insert_idusuario;
            }
            set
            {
                Oninsert_idusuarioChanging(value);
                ReportPropertyChanging("insert_idusuario");
                _insert_idusuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("insert_idusuario");
                Oninsert_idusuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _insert_idusuario;
        partial void Oninsert_idusuarioChanging(Nullable<global::System.Int32> value);
        partial void Oninsert_idusuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> update_idusuario
        {
            get
            {
                return _update_idusuario;
            }
            set
            {
                Onupdate_idusuarioChanging(value);
                ReportPropertyChanging("update_idusuario");
                _update_idusuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("update_idusuario");
                Onupdate_idusuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _update_idusuario;
        partial void Onupdate_idusuarioChanging(Nullable<global::System.Int32> value);
        partial void Onupdate_idusuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idsubtiporequerimiento
        {
            get
            {
                return _idsubtiporequerimiento;
            }
            set
            {
                OnidsubtiporequerimientoChanging(value);
                ReportPropertyChanging("idsubtiporequerimiento");
                _idsubtiporequerimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idsubtiporequerimiento");
                OnidsubtiporequerimientoChanged();
            }
        }
        private Nullable<global::System.Int32> _idsubtiporequerimiento;
        partial void OnidsubtiporequerimientoChanging(Nullable<global::System.Int32> value);
        partial void OnidsubtiporequerimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> prioridad
        {
            get
            {
                return _prioridad;
            }
            set
            {
                OnprioridadChanging(value);
                ReportPropertyChanging("prioridad");
                _prioridad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prioridad");
                OnprioridadChanged();
            }
        }
        private Nullable<global::System.Int32> _prioridad;
        partial void OnprioridadChanging(Nullable<global::System.Int32> value);
        partial void OnprioridadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private Nullable<global::System.Byte> _status;
        partial void OnstatusChanging(Nullable<global::System.Byte> value);
        partial void OnstatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_Requerimiento_proyecto", "proyecto")]
        public proyecto proyecto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<proyecto>("requerimientosModel.FK_Requerimiento_proyecto", "proyecto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<proyecto>("requerimientosModel.FK_Requerimiento_proyecto", "proyecto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<proyecto> proyectoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<proyecto>("requerimientosModel.FK_Requerimiento_proyecto", "proyecto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<proyecto>("requerimientosModel.FK_Requerimiento_proyecto", "proyecto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_Requerimiento_subtiporequerimiento", "subtiporequerimiento")]
        public subtiporequerimiento subtiporequerimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<subtiporequerimiento>("requerimientosModel.FK_Requerimiento_subtiporequerimiento", "subtiporequerimiento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<subtiporequerimiento>("requerimientosModel.FK_Requerimiento_subtiporequerimiento", "subtiporequerimiento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<subtiporequerimiento> subtiporequerimientoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<subtiporequerimiento>("requerimientosModel.FK_Requerimiento_subtiporequerimiento", "subtiporequerimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<subtiporequerimiento>("requerimientosModel.FK_Requerimiento_subtiporequerimiento", "subtiporequerimiento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_Requerimiento_usuario", "usuario")]
        public usuario usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("requerimientosModel.FK_Requerimiento_usuario", "usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("requerimientosModel.FK_Requerimiento_usuario", "usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuario> usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("requerimientosModel.FK_Requerimiento_usuario", "usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuario>("requerimientosModel.FK_Requerimiento_usuario", "usuario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_Requerimiento_usuario1", "usuario")]
        public usuario usuario1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("requerimientosModel.FK_Requerimiento_usuario1", "usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("requerimientosModel.FK_Requerimiento_usuario1", "usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuario> usuario1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("requerimientosModel.FK_Requerimiento_usuario1", "usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuario>("requerimientosModel.FK_Requerimiento_usuario1", "usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="requerimientosModel", Name="subtiporequerimiento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class subtiporequerimiento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new subtiporequerimiento object.
        /// </summary>
        /// <param name="idsubtiporequerimiento">Initial value of the idsubtiporequerimiento property.</param>
        public static subtiporequerimiento Createsubtiporequerimiento(global::System.Int32 idsubtiporequerimiento)
        {
            subtiporequerimiento subtiporequerimiento = new subtiporequerimiento();
            subtiporequerimiento.idsubtiporequerimiento = idsubtiporequerimiento;
            return subtiporequerimiento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idsubtiporequerimiento
        {
            get
            {
                return _idsubtiporequerimiento;
            }
            set
            {
                if (_idsubtiporequerimiento != value)
                {
                    OnidsubtiporequerimientoChanging(value);
                    ReportPropertyChanging("idsubtiporequerimiento");
                    _idsubtiporequerimiento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idsubtiporequerimiento");
                    OnidsubtiporequerimientoChanged();
                }
            }
        }
        private global::System.Int32 _idsubtiporequerimiento;
        partial void OnidsubtiporequerimientoChanging(global::System.Int32 value);
        partial void OnidsubtiporequerimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idtiporequerimiento
        {
            get
            {
                return _idtiporequerimiento;
            }
            set
            {
                OnidtiporequerimientoChanging(value);
                ReportPropertyChanging("idtiporequerimiento");
                _idtiporequerimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idtiporequerimiento");
                OnidtiporequerimientoChanged();
            }
        }
        private Nullable<global::System.Int32> _idtiporequerimiento;
        partial void OnidtiporequerimientoChanging(Nullable<global::System.Int32> value);
        partial void OnidtiporequerimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_Requerimiento_subtiporequerimiento", "Requerimiento")]
        public EntityCollection<Requerimiento> Requerimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Requerimiento>("requerimientosModel.FK_Requerimiento_subtiporequerimiento", "Requerimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Requerimiento>("requerimientosModel.FK_Requerimiento_subtiporequerimiento", "Requerimiento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_suttiporequerimiento_tiporequerimiento", "tiporequerimiento")]
        public tiporequerimiento tiporequerimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tiporequerimiento>("requerimientosModel.FK_suttiporequerimiento_tiporequerimiento", "tiporequerimiento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tiporequerimiento>("requerimientosModel.FK_suttiporequerimiento_tiporequerimiento", "tiporequerimiento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tiporequerimiento> tiporequerimientoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tiporequerimiento>("requerimientosModel.FK_suttiporequerimiento_tiporequerimiento", "tiporequerimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tiporequerimiento>("requerimientosModel.FK_suttiporequerimiento_tiporequerimiento", "tiporequerimiento", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="requerimientosModel", Name="tiporequerimiento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tiporequerimiento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tiporequerimiento object.
        /// </summary>
        /// <param name="idtiporequerimiento">Initial value of the idtiporequerimiento property.</param>
        public static tiporequerimiento Createtiporequerimiento(global::System.Int32 idtiporequerimiento)
        {
            tiporequerimiento tiporequerimiento = new tiporequerimiento();
            tiporequerimiento.idtiporequerimiento = idtiporequerimiento;
            return tiporequerimiento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idtiporequerimiento
        {
            get
            {
                return _idtiporequerimiento;
            }
            set
            {
                if (_idtiporequerimiento != value)
                {
                    OnidtiporequerimientoChanging(value);
                    ReportPropertyChanging("idtiporequerimiento");
                    _idtiporequerimiento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idtiporequerimiento");
                    OnidtiporequerimientoChanged();
                }
            }
        }
        private global::System.Int32 _idtiporequerimiento;
        partial void OnidtiporequerimientoChanging(global::System.Int32 value);
        partial void OnidtiporequerimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_suttiporequerimiento_tiporequerimiento", "subtiporequerimiento")]
        public EntityCollection<subtiporequerimiento> subtiporequerimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<subtiporequerimiento>("requerimientosModel.FK_suttiporequerimiento_tiporequerimiento", "subtiporequerimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<subtiporequerimiento>("requerimientosModel.FK_suttiporequerimiento_tiporequerimiento", "subtiporequerimiento", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="requerimientosModel", Name="usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuario object.
        /// </summary>
        /// <param name="idusuario">Initial value of the idusuario property.</param>
        public static usuario Createusuario(global::System.Int32 idusuario)
        {
            usuario usuario = new usuario();
            usuario.idusuario = idusuario;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idusuario
        {
            get
            {
                return _idusuario;
            }
            set
            {
                if (_idusuario != value)
                {
                    OnidusuarioChanging(value);
                    ReportPropertyChanging("idusuario");
                    _idusuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idusuario");
                    OnidusuarioChanged();
                }
            }
        }
        private global::System.Int32 _idusuario;
        partial void OnidusuarioChanging(global::System.Int32 value);
        partial void OnidusuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String clave
        {
            get
            {
                return _clave;
            }
            set
            {
                OnclaveChanging(value);
                ReportPropertyChanging("clave");
                _clave = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("clave");
                OnclaveChanged();
            }
        }
        private global::System.String _clave;
        partial void OnclaveChanging(global::System.String value);
        partial void OnclaveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idperfil
        {
            get
            {
                return _idperfil;
            }
            set
            {
                OnidperfilChanging(value);
                ReportPropertyChanging("idperfil");
                _idperfil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idperfil");
                OnidperfilChanged();
            }
        }
        private Nullable<global::System.Int32> _idperfil;
        partial void OnidperfilChanging(Nullable<global::System.Int32> value);
        partial void OnidperfilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private Nullable<global::System.Byte> _status;
        partial void OnstatusChanging(Nullable<global::System.Byte> value);
        partial void OnstatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_usuario_perfil1", "perfil")]
        public perfil perfil
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<perfil>("requerimientosModel.FK_usuario_perfil1", "perfil").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<perfil>("requerimientosModel.FK_usuario_perfil1", "perfil").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<perfil> perfilReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<perfil>("requerimientosModel.FK_usuario_perfil1", "perfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<perfil>("requerimientosModel.FK_usuario_perfil1", "perfil", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_proyectoxusuario_usuario", "proyectoxusuario")]
        public EntityCollection<proyectoxusuario> proyectoxusuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<proyectoxusuario>("requerimientosModel.FK_proyectoxusuario_usuario", "proyectoxusuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<proyectoxusuario>("requerimientosModel.FK_proyectoxusuario_usuario", "proyectoxusuario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_Requerimiento_usuario", "Requerimiento")]
        public EntityCollection<Requerimiento> Requerimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Requerimiento>("requerimientosModel.FK_Requerimiento_usuario", "Requerimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Requerimiento>("requerimientosModel.FK_Requerimiento_usuario", "Requerimiento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("requerimientosModel", "FK_Requerimiento_usuario1", "Requerimiento")]
        public EntityCollection<Requerimiento> Requerimiento1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Requerimiento>("requerimientosModel.FK_Requerimiento_usuario1", "Requerimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Requerimiento>("requerimientosModel.FK_Requerimiento_usuario1", "Requerimiento", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
